package com.westlyf.controller;

/**
 * Created by robertoguazon on 04/09/2016.
 */
public enum ControllerType {
    //viewers
    TEXT_LESSON_VIEWER,
    VIDEO_LESSON_VIEWER,
    QUIZ_EXERCISE_VIEWER,
    PRACTICAL_PRINT_EXERCISE_VIEWER,
    PRACTICAL_RETURN_EXERCISE_VIEWER,
    VIDEO_PRACTICAL_EXERCISE_VIEWER,

    //controllers
    LESSON_MAKER,
    QUIZ_EXERCISE_MAKER,
    PRACTICAL_EXERCISE_MAKER,
    VIDEO_PRACTICAL_EXERCISE_MAKER,
}
